site_name: Deployment Automation Framework For You
theme:
  name: material
  #custom_dir: overrides
  logo: images/ducks.png
  favicon: images/ducks.png
  icon:
    admonition:
      <type>: material/alert
  palette:
    scheme: default
    primary: black
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
    - toc.follow
    - navigation.sections
    - navigation.expand
    - navigation.tracking
    - content.code.annotate
nav:
  - Home: index.md
  - Overview:
    - Overview/index.md
    - Tools Installed: Overview/Tools-Installed.md
  - Deploying OCP:
    - Deploying-OCP/index.md
    - Pre-Req: Deploying-OCP/Pre-Req.md
    - Core Steps: Deploying-OCP/Core-steps.md
    - HCCX Gym: Deploying-OCP/HCCX-gym.md
    - TechZone: Deploying-OCP/TechZone.md
    - ROKS: Deploying-OCP/ROKS.md
    - Azure: Deploying-OCP/Azure.md
    - AWS: Deploying-OCP/AWS.md
    - GCP: Deploying-OCP/GCP.md
    - IBM: Deploying-OCP/IBM.md
    - KVM: Deploying-OCP/kvm.md
    - VSphere: Deploying-OCP/VSphere.md
    - Restricted Network: Deploying-OCP/Restricted-Network.md
    - TechZoneTiles: Deploying-OCP/TechZoneTiles.md
#   - Extra Features: Deploying-OCP/extra_features.md
#    - Pre-built Clusters: Deploying-OCP/Pre-Built-Cluster.md
  - Cloud Paks:
    - Cloud-Paks/index.md
    - Business Automation: Cloud-Paks/Business-Automation.md
    - Data: Cloud-Paks/Data.md
    - Integration: Cloud-Paks/Integration.md
    - Watson AIOPS: Cloud-Paks/Watson-AIOPS.md
    - Security: Cloud-Paks/Security.md
    - WebSphere Automation: Cloud-Paks/WebSphere-Automation.md
  - Supporting Software:
    - Supporting-Software/index.md
    - Bastion: Supporting-Software/Bastion.md
    - DB2: Supporting-Software/DB2.md
    - IBM LDAP: Supporting-Software/IBM-LDAP.md
    - Turbo: Supporting-Software/Turbo.md
  #- Overrides:
  #  - overrides/index.md
  #  - Daffy: overrides/daffy.md
  #  - OpenShift: overrides/ocp.md
  #  - Platforms:
  #      - overrides/cloudpaks/index.md
  #      - AWS: overrides/platforms/aws.md
  #      - Azure: overrides/platforms/azure.md
  #      - Google: overrides/platforms/gcp.md
  #      - VSphere: overrides/platforms/vsphere.md
  #  - Cloud Paks:
  #      - overrides/platforms/index.md
  #      - Business Automation: overrides/cloudpaks/cp4ba.md
  #      - Data: overrides/cloudpaks/cp4d.md
  #      - Integration: overrides/cloudpaks/cp4i.md
  #      - Security: overrides/cloudpaks/cp4security.md
  #      - Wations AIOps: overrides/cloudpaks/cp4waiops.md
  #  - Software:
  #      - DB2: overrides/software/db2.md
  #      - LDAP: overrides/software/ldap.md
  #      - Turbonomics: overrides/software/turbonomics.md
  - Tips & Tricks:
    - Common Issues: Tips-and-Tricks/Common-Issues.md
    - Common Commands: Tips-and-Tricks/Common-Commands.md
    - Environment File: Tips-and-Tricks/Environment-File.md
    - Edit Files: Tips-and-Tricks/Edit-Files.md
    - Daffy Upgrade: Tips-and-Tricks/Upgrade.md
    - OC Commands: Tips-and-Tricks/occommands.md
  - Request Forms:
    - Request-Forms/index.md
    #- Demo Request: Request-Forms/Demo-Request.md
    #- Feature Request: Request-Forms/Feature-Requests.md
    #- Get Involved: Request-Forms/Get-Involved.md
    #- POC Request Form: Request-Forms/POC-Request-Form.md
    #- Training: Request-Forms/Training.md
    #- L200 Adv Training: Request-Forms/L200-Adv-Training.md
    #- Meet The teamm 2: Meet-the-Team/Meat-the-Team.md
    #- Workstreams: Meet-the-Team/Workstreams.md
  - Market Leaders : Markets.md
  - App Store :
    - App Store: AppStore/index.md
    - Information: AppStore/info.md
    - IBM Sterling B2B Installer: AppStore/IBMSterlingB2B.md
    - IBM Daffy CLI Configurator: AppStore/IBMDaffyCLIConfigurator.md
    - IBM CP4D Backup & Restore: AppStore/CP4DBackupRestore.md
  - More:
    - FAQ: More/FAQ/index.md
    - Glossary: More/Glossary.md
    - Common Errors: More/CommonErrors.md
    - Deployment Estimates: More/FAQ/Deployment-Estimates.md
    - IBM Entitlement Keys: More/FAQ/IBM-Entitlement-Keys.md
    - Secure your Bastion:  More/secure-server-ssh-only-login.md
    - Meet the Team: Meet-the-Team.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - meta
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 5
  - pymdownx.superfences
  - pymdownx.highlight:
    #  anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.keys
  #- pymdownx.magiclink
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.inlinehilite
extra_css:
    - css/extra.css
    - css/code.css
    - css/button.css
copyright: Copyright &copy; 2021 - 2022 IBM Black Belt Team
extra:
  social:
    - icon: fontawesome/solid/paper-plane
      name: Feedback on Daffy
      link: mailto:feedback@daffy-installer.com
    - icon: fontawesome/brands/youtube
      name: Daffy YouTube Channel
      link: https://www.youtube.com/@daffyinstaller
  analytics:
    provider: google
    property: G-L33BY57ZVG
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target=_blank>feedback form</a>.
  generator: false
